services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=leaderboard'
      - 'POSTGRES_PASSWORD=leaderboard'
      - 'POSTGRES_USER=leaderboard'
    ports:
      - '5432'
  kafka:
    image: docker.io/bitnami/kafka:3.8.1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

  redpanda:
    image: 'redpandadata/console:latest'
    environment:
      - KAFKA_BROKERS=kafka:9092
    ports:
      - '9595:8080'
    depends_on:
      - kafka